### ISSUE TITLE
Key should not contain keypath separator ValueError - limits the supportable YAML

### ISSUE THREAD

**Issue by davesargrad** [fabiocaccamo/python-benedict#220]
I have a yaml input,
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtm-dep
  labels:
    app: vtm
spec:
  selector:
    matchLabels:
      app: vtm
  replicas: 1
  template:
    metadata:
      labels:
        app: vtm
    spec:
      containers:
        - name: vtm-dep
          image: aaa:5000/vtm:0.2.0
          volumeMounts:
          resources:
            limits:
              nvidia.com/gpu: 1
      tolerations:
      imagePullSecrets:
        - name: docker-1-reg-secret
      volumes:

```

 and the following code:
`    d = benedict.from_yaml(args.input)`

I see the following error:
`ValueError: Key should not contain keypath separator '.', found: 'nvidia.com/gpu'.`

This is a valid yaml file, yet benedict does not seem to support such keys. This stands in the way from my being able to use benedict.

Is there a solution that I am missing?
