### ISSUE TITLE
Broken Serialization with benedict attributes

### ISSUE THREAD

**Issue by JJGO** [fabiocaccamo/python-benedict#89]
**Python version**
Python 3.9.12

**Package version**
master (installed with `python -m pip install git+https://github.com/fabiocaccamo/python-benedict.git`)

**Current behavior (bug description)**
If a benedict gets assigned to a key serialization does not convert it to a regular dict

```python
x = benedict()
x['a'] = benedict({'b': 2})
print(x.to_yaml())
```

outputs

```
a: !!python/object/new:benedict.dicts.benedict
  dictitems:
    b: 2
  state:
    _dict:
      b: 2
    _keypath_separator: .
    _pointer: true
```

**Expected behavior**

```python
x = benedict()
x['a'] = benedict({'b': 2})
print(x.to_yaml())
```

outputs

```
a:
  b: 2
```
